apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: crypto-assets-subledger-app
  namespace: dev
  labels:
    app.kubernetes.io/name: crypto-assets-subledger-app
spec:
  gateway: crypto-assets-subledger-aws-gateway.aws-dns.svc.cluster.local
  rules:
    - accessStrategies:
        - handler: allow
          config: {}
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /.*
  service:
    host: app.cryptoassetssubledger.com
    name: crypto-rates-service-app
    port: 5000